# Generated by Django 4.2.4 on 2023-08-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=259, unique_for_date='publish'),
        ),
    ]
